<?php echo $this->doctype(); ?>

<html lang="en" dir='<?=$this->direction?>'>
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 ' . $this->translate('Ideablog spike'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php
    if($this->direction == "rtl"){
      $this->headLink()->appendStylesheet($this->basePath() . '/css/style-rtl.css');
    }
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
      ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
      ->prependStylesheet($this->basePath() . '/css/style.css')
      ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
    
    
    ?>

    <!-- Scripts -->
    <?php
    echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
      ->prependFile($this->basePath() . '/js/jquery.min.js')
    ?>

  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('topic') ?>"><?php echo $this->translate('Skeleton Application') ?></a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url('topic') ?>"><?php echo $this->translate('Topics') ?></a></li>
            </ul>
          </div><!--/.nav-collapse -->
          <div class="dropdown" style="float:right">
          <? echo $this->partial('layout/languages.phtml', array(
            'lang' => array(
              'English'  => 'en_US',
              'Hebrew' => 'he_HE',
            ),
            'selected' => $this->lang
          )); ?>
        </div>
        </div>        
      </div>
    </div>
    <div class="container">
    <?php echo $this->content; ?>
    </div> <!-- /container -->
    <footer class='muted'>
      <p>&copy; 2012 - <?php echo date('Y') ?> by <span style='text-decoration: line-through;'>ZEND</span> DDI Technologies . <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
<?php echo $this->inlineScript() ?>
  </body>
</html>
