<?php
$title = 'Topics Overview';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($topics as $topic) : ?>
      <tr>
        <td>
          <a href="<?=$this->url('topic', array('action'=>'show', 'id' => $topic->getId()))?>"><?= $this->escapeHtml($topic->getTitle()); ?></a>
        </td>
        <td>
          <a class='btn btn-mini' href="<?= $this->url('topic', array('action' => 'edit', 'id' => $topic->getId())); ?>">Edit this Topic</a>
          <a class='btn btn-mini' href="<?= $this->url('topic', array('action' => 'delete', 'id' => $topic->getId())); ?>">Delete this Topic</a></li>
        </td>
      </tr>
    <?php endforeach; ?>
  </tbody>  
</table>
<a class='btn btn-primary' href="<?= $this->url('topic', array('action' => 'add')); ?>">Add new Topic</a>