<?php
$title = $topic->getTitle();
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
  <?php echo $this->escapeHtml($topic->getContent()); ?>
</p>
<?php foreach ($replies as $reply) : ?>
<article>
  <p>Created by <?php echo $reply->getCreatedBy()->getName(); ?> on <?php echo $reply->getCreatedAt(); ?></p>
  <p>
    <?php echo $this->escapeHtml($reply->getContent());?>
  </p>
</article>
<?php endforeach; ?>

<?php
$form->setAttribute('action', $this->url('reply', array('action'=>'add')))
     ->prepare();

echo $this->form()->openTag($form);

$postFieldset = $form->get('reply');

echo $this->formHidden($form->get('security'));
echo $this->formHidden($postFieldset->get('id'));
echo $this->formHidden($postFieldset->get('topic'));
echo $this->formRow($postFieldset->get('content'));

echo $this->formInput($form->get('submit'));

echo $this->form()->closeTag($form);
?>